### ISSUE TITLE
Muddy Trees are not generating with Willow Logs nor Leaves

### ISSUE THREAD

**Issue by SocialNyetwork** [thelegitdolt/Dolt-Compat#1]
![Muddy Oak Trees](https://user-images.githubusercontent.com/130416999/236089130-1d18503c-def5-476a-ae38-8df8e699bdb0.png)

**Comment by thelegitdolt** [comment]
noted

**Comment by thelegitdolt** [comment]
fixed in next indev patch

**Comment by thelegitdolt** [comment]
patch out lol
