### ISSUE TITLE
Biome Backport Compat

### ISSUE THREAD

**Issue by Swagboi7** [thelegitdolt/Dolt-Compat#2]
https://www.curseforge.com/minecraft/mc-mods/biome-backport

I wouldn't mind some Environmental/Biome Backport compat where the cherry trees in the Environmental biomes are replaced with the backported ones from Biome Backport.

**Comment by thelegitdolt** [comment]
Sorry, but I do not support mods that I don't play. However, you can do what you're looking for pretty easily using https://www.curseforge.com/minecraft/mc-mods/block-swap. Hope that helps!

**Comment by Swagboi7** [comment]
Oh damn this mod looks incredibly helpful for something else I'm dealing with
