### ISSUE TITLE
Request - No Neapolitan dependency?

### ISSUE THREAD

**Issue by LeonKappaX** [thelegitdolt/Dolt-Compat#4]
Hey! I've been playing around with your mod for some time now and I really enjoy the stuff it adds. However, I am not a big fan of Neapolitan and don't want to include it in a modpack I am working on.
So I was wondering if it could be possible for you to make it so Neapolitan isn't required for the mod to load!
It's okay if it isn't possible, no pressure

**Comment by thelegitdolt** [comment]
sure

**Comment by thelegitdolt** [comment]
check newest release
